name: rustfmt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        rustup toolchain install nightly --allow-downgrade -c rustfmt
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Check
      run: cargo +nightly fmt -- --check
